'use server'

// Meal-plan + shopping-list server actions. One mealPlan row per user; the
// row holds a set of picked recipes (with scale) and the resolved shopping
// list. When recipes change, the auto-rows of the shopping list are
// regenerated by re-parsing every picked recipe's ingredients, scaling
// them, and merging same-(item, unit) lines. Manual rows are left alone.

import { and, asc, eq, inArray, sql as drizzleSql } from 'drizzle-orm'
import { revalidatePath } from 'next/cache'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { mealPlans, mealPlanRecipes, shoppingLists, shoppingListItems, notes } from '@/lib/db/schema'
import { decryptNote } from '@/lib/crypto'
import {
  extractIngredients,
  parseIngredient,
  scaleIngredient,
  renderIngredient,
  mergeIngredients,
  type ParsedIngredient,
} from '@/lib/recipe-parse'

async function requireUser() {
  const session = await auth()
  if (!session?.user?.id) throw new Error('Unauthorized')
  if (session.user.role === 'readonly') throw new Error('Read-only access.')
  return session
}

function bumpUpdatedPaths() {
  revalidatePath('/meal-plan')
  revalidatePath('/meal-plan/grocery')
  revalidatePath('/meal-plan/quick-pick')
}

/**
 * Lazy lookup of the meal plan's "From Meal Plan" auto-list — the
 * destination for recipe-generated rows AND the default destination
 * for manual / Quick-Pick items when no other list is specified.
 * Creates it on the fly for any plan that doesn't have one yet
 * (covers users who pre-date the multi-list migration).
 */
async function ensureAutoListId(planId: string): Promise<string> {
  const existing = await db
    .select({ id: shoppingLists.id })
    .from(shoppingLists)
    .where(and(eq(shoppingLists.mealPlanId, planId), eq(shoppingLists.isAutoMealPlan, true)))
    .then((r) => r[0])
  if (existing) return existing.id
  const [created] = await db
    .insert(shoppingLists)
    .values({ mealPlanId: planId, name: 'From Meal Plan', isAutoMealPlan: true, sortOrder: 0 })
    .returning({ id: shoppingLists.id })
  return created.id
}

// ─── Read / ensure ───────────────────────────────────────────────────────────

/** Lazy-upsert a mealPlan row for the current user, returns its id. */
export async function ensureMealPlan(): Promise<string> {
  const session = await requireUser()
  const existing = await db
    .select({ id: mealPlans.id })
    .from(mealPlans)
    .where(eq(mealPlans.userId, session.user.id))
    .then((r) => r[0])
  if (existing) return existing.id

  const [created] = await db
    .insert(mealPlans)
    .values({ userId: session.user.id })
    .returning({ id: mealPlans.id })
  return created.id
}

export interface MealPlanRecipeRow {
  recipeId: string
  scale: number
  title: string
  servings: number | null
}

export interface ShoppingListRow {
  id: string
  text: string
  itemKey: string | null
  recipeIds: string[]
  isManual: boolean
  purchased: boolean
  sortOrder: number
  /**
   * True when this row should appear on the grocery trip.
   *
   * - Manual rows are ALWAYS selected (the user typed them in on
   *   purpose).
   * - Auto-rows (from picked recipes) are selected ONLY when the
   *   user has explicitly ticked them — their itemKey lives in the
   *   meal plan's selectedItemKeys list. Default is unchecked /
   *   not-on-the-list; this lets the user scan the full preview and
   *   pick out exactly what she still needs to buy.
   *
   * Computed at read time so it survives recipe scale changes that
   * rewrite each row's display text but preserve its itemKey.
   */
  selected: boolean
}

export interface MealPlanData {
  id: string
  recipes: MealPlanRecipeRow[]
  shoppingList: ShoppingListRow[]
}

/**
 * Snapshot of the current user's meal plan for /meal-plan + /meal-plan/grocery.
 * Joins picked-recipe titles + servings so the UI doesn't need a second
 * query. Computes `selected` per shopping-list row from the plan's
 * selectedItemKeys set so the preview UI can show check state without a
 * second roundtrip.
 */
export async function getMealPlan(): Promise<MealPlanData> {
  const planId = await ensureMealPlan()

  const planRow = await db
    .select({ selectedItemKeys: mealPlans.selectedItemKeys })
    .from(mealPlans)
    .where(eq(mealPlans.id, planId))
    .then((r) => r[0])
  const selectedSet = new Set(planRow?.selectedItemKeys ?? [])

  const picked = await db
    .select({
      recipeId: mealPlanRecipes.recipeId,
      scale: mealPlanRecipes.scale,
      title: notes.title,
      servings: notes.servings,
    })
    .from(mealPlanRecipes)
    .leftJoin(notes, eq(mealPlanRecipes.recipeId, notes.id))
    .where(eq(mealPlanRecipes.mealPlanId, planId))
    .orderBy(asc(mealPlanRecipes.sortOrder), asc(mealPlanRecipes.createdAt))

  // Meal-plan preview shows ONLY the auto-list (the recipe-derived
  // rows + any manual additions made before lists existed). Other
  // user-created lists ("Heather's weekly" etc.) are managed from
  // /meal-plan/grocery's list switcher.
  const autoListId = await ensureAutoListId(planId)
  let items = await db
    .select()
    .from(shoppingListItems)
    .where(eq(shoppingListItems.shoppingListId, autoListId))
    .orderBy(asc(shoppingListItems.sortOrder), asc(shoppingListItems.createdAt))

  // Self-heal: auto-rows inserted before item_key existed (or before the
  // regenerator wrote it) have item_key = NULL, which makes the skip
  // toggle disappear from the preview. If we spot any, re-run the
  // regenerator once — it overwrites all auto-rows with itemKey set and
  // future reads skip this branch.
  const hasMissingItemKey = items.some((i) => !i.isManual && i.itemKey == null)
  if (hasMissingItemKey) {
    await regenerateAutoItems(planId)
    items = await db
      .select()
      .from(shoppingListItems)
      .where(eq(shoppingListItems.shoppingListId, autoListId))
      .orderBy(asc(shoppingListItems.sortOrder), asc(shoppingListItems.createdAt))
  }

  return {
    id: planId,
    recipes: picked.map((r) => ({
      recipeId: r.recipeId,
      scale: r.scale,
      title: r.title ?? '(deleted recipe)',
      servings: r.servings,
    })),
    shoppingList: items.map((i) => ({
      id: i.id,
      text: i.text,
      itemKey: i.itemKey,
      recipeIds: i.recipeIds ?? [],
      isManual: i.isManual,
      purchased: i.purchased,
      sortOrder: i.sortOrder,
      // Manual rows are always on the list; auto-rows only when ticked.
      selected: i.isManual || (i.itemKey != null && selectedSet.has(i.itemKey)),
    })),
  }
}

/**
 * Items for a specific named list. Used by the grocery view's list
 * switcher. Auto-list items get the `selected` flag computed from
 * mealPlans.selectedItemKeys; user-created lists are always-selected
 * (their items were typed in by hand, no opt-in needed). Returns
 * null when the list doesn't belong to the current user's meal plan.
 */
export async function getShoppingListItems(listId: string): Promise<ShoppingListRow[] | null> {
  const planId = await ensureMealPlan()
  const list = await db
    .select()
    .from(shoppingLists)
    .where(and(eq(shoppingLists.id, listId), eq(shoppingLists.mealPlanId, planId)))
    .then((r) => r[0])
  if (!list) return null

  const planRow = await db
    .select({ selectedItemKeys: mealPlans.selectedItemKeys })
    .from(mealPlans)
    .where(eq(mealPlans.id, planId))
    .then((r) => r[0])
  const selectedSet = new Set(planRow?.selectedItemKeys ?? [])

  const items = await db
    .select()
    .from(shoppingListItems)
    .where(eq(shoppingListItems.shoppingListId, listId))
    .orderBy(asc(shoppingListItems.sortOrder), asc(shoppingListItems.createdAt))

  return items.map((i) => ({
    id: i.id,
    text: i.text,
    itemKey: i.itemKey,
    recipeIds: i.recipeIds ?? [],
    isManual: i.isManual,
    purchased: i.purchased,
    sortOrder: i.sortOrder,
    // Auto-list: opt-in via selectedItemKeys. User-created list: always on.
    selected: !list.isAutoMealPlan
      ? true
      : i.isManual || (i.itemKey != null && selectedSet.has(i.itemKey)),
  }))
}

// ─── Recipe pick / scale / remove ────────────────────────────────────────────

export async function addRecipeToPlan(recipeId: string, scale: number = 1) {
  await requireUser()
  const planId = await ensureMealPlan()

  // Upsert via unique index (mealPlanId, recipeId).
  await db
    .insert(mealPlanRecipes)
    .values({ mealPlanId: planId, recipeId, scale: clampScale(scale) })
    .onConflictDoUpdate({
      target: [mealPlanRecipes.mealPlanId, mealPlanRecipes.recipeId],
      set: { scale: clampScale(scale) },
    })

  await regenerateAutoItems(planId)
  bumpUpdatedPaths()
  return { success: true }
}

export async function setRecipeScale(recipeId: string, scale: number) {
  await requireUser()
  const planId = await ensureMealPlan()
  await db
    .update(mealPlanRecipes)
    .set({ scale: clampScale(scale) })
    .where(and(eq(mealPlanRecipes.mealPlanId, planId), eq(mealPlanRecipes.recipeId, recipeId)))
  await regenerateAutoItems(planId)
  bumpUpdatedPaths()
  return { success: true }
}

export async function removeRecipeFromPlan(recipeId: string) {
  await requireUser()
  const planId = await ensureMealPlan()
  await db
    .delete(mealPlanRecipes)
    .where(and(eq(mealPlanRecipes.mealPlanId, planId), eq(mealPlanRecipes.recipeId, recipeId)))
  await regenerateAutoItems(planId)
  bumpUpdatedPaths()
  return { success: true }
}

// ─── Manual items + checkbox ─────────────────────────────────────────────────

export async function addManualItem(text: string, listId?: string) {
  await requireUser()
  const trimmed = text.trim()
  if (!trimmed) return { error: 'Empty item.' }
  const planId = await ensureMealPlan()
  const targetListId = listId ?? (await ensureAutoListId(planId))
  await db.insert(shoppingListItems).values({
    mealPlanId: planId,
    shoppingListId: targetListId,
    text: trimmed,
    recipeIds: [],
    isManual: true,
    purchased: false,
    sortOrder: -1, // floats to top
  })
  bumpUpdatedPaths()
  return { success: true }
}

/**
 * Bulk version of addManualItem — used by the Quick-Pick page so a
 * stack of 30 checked staples becomes ONE insert + ONE revalidate
 * instead of N round-trips. Dedupes empty strings; keeps duplicates
 * the user explicitly typed (some shoppers want "milk" twice).
 * Optional listId targets a specific named list (Heather's, etc.);
 * omitting it falls back to the meal plan's auto-list.
 */
export async function addBulkManualItems(items: string[], listId?: string) {
  await requireUser()
  const cleaned = items.map((t) => t.trim()).filter(Boolean)
  if (cleaned.length === 0) return { success: true, inserted: 0 }
  const planId = await ensureMealPlan()
  const targetListId = listId ?? (await ensureAutoListId(planId))
  await db.insert(shoppingListItems).values(
    cleaned.map((text) => ({
      mealPlanId: planId,
      shoppingListId: targetListId,
      text,
      recipeIds: [],
      isManual: true,
      purchased: false,
      sortOrder: -1, // floats to top
    })),
  )
  bumpUpdatedPaths()
  return { success: true, inserted: cleaned.length }
}

export async function removeShoppingItem(itemId: string) {
  await requireUser()
  await db.delete(shoppingListItems).where(eq(shoppingListItems.id, itemId))
  bumpUpdatedPaths()
  return { success: true }
}

export async function toggleShoppingItemPurchased(itemId: string) {
  await requireUser()
  const row = await db
    .select({
      id: shoppingListItems.id,
      purchased: shoppingListItems.purchased,
      mealPlanId: shoppingListItems.mealPlanId,
    })
    .from(shoppingListItems)
    .where(eq(shoppingListItems.id, itemId))
    .then((r) => r[0])
  if (!row) return { error: 'Item not found.' }

  const nextPurchased = !row.purchased
  let nextSortOrder = 0
  if (nextPurchased) {
    // Push to bottom: max sortOrder + 1.
    const max = await db
      .select({ m: drizzleSql<number>`max(${shoppingListItems.sortOrder})` })
      .from(shoppingListItems)
      .where(eq(shoppingListItems.mealPlanId, row.mealPlanId))
      .then((r) => r[0]?.m ?? 0)
    nextSortOrder = (max ?? 0) + 1
  } else {
    // Float back to top.
    nextSortOrder = -1
  }

  await db
    .update(shoppingListItems)
    .set({ purchased: nextPurchased, sortOrder: nextSortOrder })
    .where(eq(shoppingListItems.id, itemId))
  bumpUpdatedPaths()
  return { success: true, purchased: nextPurchased }
}

export async function clearMealPlan() {
  await requireUser()
  const planId = await ensureMealPlan()
  await db.delete(mealPlanRecipes).where(eq(mealPlanRecipes.mealPlanId, planId))
  await db.delete(shoppingListItems).where(eq(shoppingListItems.mealPlanId, planId))
  // Reset the opt-in selections so the next plan starts with nothing
  // checked.
  await db.update(mealPlans).set({ selectedItemKeys: null }).where(eq(mealPlans.id, planId))
  bumpUpdatedPaths()
  return { success: true }
}

/**
 * Flip the user's "yes, put this on the grocery list" tick for an
 * auto-row. The selection is stored on the plan keyed by ingredient
 * name (itemKey) so it survives recipe scale changes — which rewrite
 * the row text but preserve the itemKey. Default state is UNCHECKED:
 * the user sees every consolidated ingredient and picks the ones
 * she's missing. No-op for manual rows or rows with no itemKey
 * (manual rows are always on the list).
 */
export async function toggleItemSelected(itemKey: string) {
  await requireUser()
  const planId = await ensureMealPlan()
  const trimmed = itemKey.trim()
  if (!trimmed) return { success: true }

  const plan = await db
    .select({ selected: mealPlans.selectedItemKeys })
    .from(mealPlans)
    .where(eq(mealPlans.id, planId))
    .then((r) => r[0])
  const current = plan?.selected ?? []
  const isSelected = current.includes(trimmed)
  const next = isSelected ? current.filter((k) => k !== trimmed) : [...current, trimmed]
  await db
    .update(mealPlans)
    .set({ selectedItemKeys: next.length > 0 ? next : null, updatedAt: new Date() })
    .where(eq(mealPlans.id, planId))
  bumpUpdatedPaths()
  return { success: true, selected: !isSelected }
}

// ─── Internals ───────────────────────────────────────────────────────────────

function clampScale(n: number): number {
  if (!Number.isFinite(n)) return 1
  // Round to the nearest 0.5 step so the float column stays clean and
  // the UI stepper's 0.5 increments survive a round-trip.
  const stepped = Math.round(n * 2) / 2
  if (stepped < 0.5) return 0.5
  if (stepped > 10) return 10
  return stepped
}

/**
 * Re-derive the auto rows of the shopping list from the current set of
 * picked recipes. Manual rows (isManual = true) are preserved untouched.
 *
 * Steps:
 *  1. Read all mealPlanRecipes for this plan + their note.content.
 *  2. Decrypt each, extract `## Ingredients` lines, parse + scale, tag with recipe id.
 *  3. Merge same-(item, unit) across all picks.
 *  4. Wipe the existing auto rows, insert fresh rows with the merged output.
 *
 * Failure to read a recipe (deleted, encryption corrupt) just skips it —
 * the rest of the plan still renders.
 */
async function regenerateAutoItems(planId: string) {
  const picks = await db
    .select({ recipeId: mealPlanRecipes.recipeId, scale: mealPlanRecipes.scale })
    .from(mealPlanRecipes)
    .where(eq(mealPlanRecipes.mealPlanId, planId))

  // Auto rows live in the meal-plan's auto-list — user-created
  // named lists ("Heather's", etc.) are untouched by regen.
  const autoListId = await ensureAutoListId(planId)

  if (picks.length === 0) {
    // Wipe auto rows; manual rows in the auto-list survive (they
    // were added before lists existed and now belong here).
    await db.delete(shoppingListItems).where(
      and(
        eq(shoppingListItems.shoppingListId, autoListId),
        eq(shoppingListItems.isManual, false),
      ),
    )
    return
  }

  const recipeIds = picks.map((p) => p.recipeId)
  const recipes = await db
    .select({ id: notes.id, content: notes.content })
    .from(notes)
    .where(inArray(notes.id, recipeIds))
  const contentById = new Map(recipes.map((r) => [r.id, r.content]))

  const allParsed: ParsedIngredient[] = []
  for (const pick of picks) {
    const encryptedContent = contentById.get(pick.recipeId)
    if (!encryptedContent) continue
    let plain = ''
    try {
      const decrypted = decryptNote({ content: encryptedContent })
      plain = decrypted.content
    } catch {
      plain = encryptedContent
    }
    const lines = extractIngredients(plain)
    for (const line of lines) {
      const parsed = parseIngredient(line, [pick.recipeId])
      const scaled = scaleIngredient(parsed, pick.scale)
      allParsed.push(scaled)
    }
  }

  const merged = mergeIngredients(allParsed)

  // Wipe + re-insert in a single transaction-ish flow.
  await db.delete(shoppingListItems).where(
    and(
      eq(shoppingListItems.shoppingListId, autoListId),
      eq(shoppingListItems.isManual, false),
    ),
  )

  if (merged.length > 0) {
    await db.insert(shoppingListItems).values(
      merged.map((m, idx) => ({
        mealPlanId: planId,
        shoppingListId: autoListId,
        text: renderIngredient(m),
        itemKey: m.item || null,
        recipeIds: m.recipeIds,
        isManual: false,
        purchased: false,
        sortOrder: idx,
      })),
    )
  }
}
